### ISSUE TITLE
Crash when trying to log in with Google account

### ISSUE THREAD

**Issue by johanw666** [evermind-zz/AuroraStore#1]
Commit 652cd31 builds and starts OK with anonymous mode. Release build on a Sony Z1 compact, Android 4.4.4. Downloading apk's from Google Play works.

When I try to login  with Google the app crashes before I can enter my user ID.

Relevant Logcat output (I can send the entire logfile if you want it):

```
    12-20 16:55:13.645 I/ActivityManager(1374): Displayed com.aurora.store.legacy/com.aurora.store.ui.accounts.AccountsActivity: +231ms
    12-20 16:55:13.655 I/HK/LatinKbdBaseView(1665): closing org.pocketworkstation.pckeyboard.LatinKeyboardView{4331c800 V.ED.... ......ID 0,0-720,412 #7f07000a app:id/LatinkeyboardBaseView}
    12-20 16:55:13.715 I/ActivityManager(10703): Timeline: Activity_idle id: android.os.BinderProxy@448091b8 time:573243
    12-20 16:55:13.865 I/ActivityManager(1374): Timeline: Activity_windows_visible id: ActivityRecord{44590060 u0 com.aurora.store.legacy/com.aurora.store.ui.accounts.AccountsActivity t11} time:573390
    12-20 16:55:15.525 D/StatusBar.NetworkController(1477): refreshViews: Data not connected!! Set no data type icon / Roaming
    12-20 16:55:16.205 D/SonySWEffect(520): PARAM_CA_CHSEP Clear Stereo Off(0x80000001)
    12-20 16:55:16.215 D/SonySWEffect(520): Unsupported frame count 240
    12-20 16:55:16.295 D/dalvikvm(10703): GC_CONCURRENT freed 9941K, 18% free 49532K/59760K, paused 8ms+12ms, total 108ms
    12-20 16:55:16.295 D/dalvikvm(10703): WAIT_FOR_CONCURRENT_GC blocked 72ms
    12-20 16:55:16.315 W/Glide   (10703): Load failed for  with size [192x192]
    12-20 16:55:16.315 W/Glide   (10703): class j.c.a.q.o.r: Failed to load resource
    12-20 16:55:16.525 D/StatusBar.NetworkController(1477): refreshViews: Data not connected!! Set no data type icon / Roaming
    12-20 16:55:17.275 D/SonySWEffect(520): PARAM_CA_CHSEP Clear Stereo Off(0x80000001)
    12-20 16:55:17.285 I/ActivityManager(10703): Timeline: Activity_launch_request id:com.aurora.store.legacy time:576812
    12-20 16:55:17.285 D/SonySWEffect(520): Unsupported frame count 240
    12-20 16:55:17.285 I/ActivityManager(1374): START u0 {cmp=com.aurora.store.legacy/com.aurora.store.ui.single.activity.GoogleLoginActivity} from pid 10703
    12-20 16:55:17.305 I/dalvikvm(10703): Could not find method android.webkit.CookieManager.removeAllCookies, referenced from method com.aurora.store.ui.single.activity.GoogleLoginActivity.onCreate
    12-20 16:55:17.305 W/dalvikvm(10703): VFY: unable to resolve virtual method 2772: Landroid/webkit/CookieManager;.removeAllCookies (Landroid/webkit/ValueCallback;)V
    12-20 16:55:17.305 D/dalvikvm(10703): VFY: replacing opcode 0x6e at 0x0038
    12-20 16:55:17.355 W/chromium(10703): [WARNING:proxy_service.cc(890)] PAC support disabled because there is no system implementation
    12-20 16:55:17.405 D/AndroidRuntime(10703): Shutting down VM
    12-20 16:55:17.405 W/dalvikvm(10703): threadid=1: thread exiting with uncaught exception (group=0x415a3d88)
    12-20 16:55:17.405 E/AndroidRuntime(10703): FATAL EXCEPTION: main
    12-20 16:55:17.405 E/AndroidRuntime(10703): Process: com.aurora.store.legacy, PID: 10703
    12-20 16:55:17.405 E/AndroidRuntime(10703): java.lang.NoSuchMethodError: android.webkit.CookieManager.removeAllCookies
    12-20 16:55:17.405 E/AndroidRuntime(10703): 	at com.aurora.store.ui.single.activity.GoogleLoginActivity.onCreate(GoogleLoginActivity.java:10)
    12-20 16:55:17.405 E/AndroidRuntime(10703): 	at android.app.Activity.performCreate(Activity.java:5231)
    12-20 16:55:17.405 E/AndroidRuntime(10703): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
    12-20 16:55:17.405 E/AndroidRuntime(10703): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2201)
    12-20 16:55:17.405 E/AndroidRuntime(10703): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2286)
    12-20 16:55:17.405 E/AndroidRuntime(10703): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
    12-20 16:55:17.405 E/AndroidRuntime(10703): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1246)
    12-20 16:55:17.405 E/AndroidRuntime(10703): 	at android.os.Handler.dispatchMessage(Handler.java:102)
    12-20 16:55:17.405 E/AndroidRuntime(10703): 	at android.os.Looper.loop(Looper.java:212)
    12-20 16:55:17.405 E/AndroidRuntime(10703): 	at android.app.ActivityThread.main(ActivityThread.java:5135)
    12-20 16:55:17.405 E/AndroidRuntime(10703): 	at java.lang.reflect.Method.invokeNative(Native Method)
    12-20 16:55:17.405 E/AndroidRuntime(10703): 	at java.lang.reflect.Method.invoke(Method.java:515)
    12-20 16:55:17.405 E/AndroidRuntime(10703): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
    12-20 16:55:17.405 E/AndroidRuntime(10703): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
    12-20 16:55:17.405 E/AndroidRuntime(10703): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    12-20 16:55:17.405 E/AndroidRuntime(10703): 	at dalvik.system.NativeStart.main(Native Method)
    12-20 16:55:17.415 D/ActivityManager(1374): New dropbox entry: com.aurora.store.legacy, data_app_crash, 77c6621f-9481-4f39-b7f6-8a2420afe5f4
    12-20 16:55:17.415 W/ActivityManager(1374):   Force finishing activity com.aurora.store.legacy/com.aurora.store.ui.single.activity.GoogleLoginActivity
    12-20 16:55:17.425 W/ResourceType(1374): CREATING STRING CACHE OF 44 bytes
    12-20 16:55:17.425 W/ActivityManager(1374):   Force finishing activity com.aurora.store.legacy/com.aurora.store.ui.accounts.AccountsActivity
    12-20 16:55:17.495 I/CrashMonitor(10579): CrashMonitorServiceBroadcastReceiver: Forwarding intent: android.intent.action.DROPBOX_ENTRY_ADDED tag: data_app_crash
    12-20 16:55:17.535 I/ActivityManager(1374): Delay finish: com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
    12-20 16:55:17.545 I/ActivityManager(1374): Resuming delayed broadcast
    12-20 16:55:17.565 I/CrashMonitor(10579): CrashMonitorService: Service started...
    12-20 16:55:17.575 I/CrashMonitor(10579): CrashMonitorService: action: android.intent.action.DROPBOX_ENTRY_ADDED
    12-20 16:55:17.725 I/CrashMonitor(10579): CrashMonitorService: Service stopped...
    12-20 16:55:17.725 W/ContextImpl(8077): Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1527 android.content.ContextWrapper.startService:494 android.content.ContextWrapper.startService:494 com.sonymobile.phoneusage.service.plugin.crashstatus.CrashStatusReceiver.onReceiveInternal:31 com.sonymobile.phoneusage.service.DeviceUsageReceiver.onReceive:27 
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): Problem with socket or streams.
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): java.net.ConnectException: failed to connect to www.google-analytics.com/127.0.0.1 (port 80): connect failed: ECONNREFUSED (Connection refused)
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): 	at libcore.io.IoBridge.connect(IoBridge.java:118)
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): 	at libcore.io.IoBridge.connect(Native Method)
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:460)
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): 	at java.net.Socket.connect(Socket.java:838)
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): 	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:119)
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): 	at com.google.android.apps.analytics.PipelinedRequester.maybeOpenConnection(Unknown Source)
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): 	at com.google.android.apps.analytics.PipelinedRequester.addRequest(Unknown Source)
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): 	at com.google.android.apps.analytics.NetworkDispatcher$DispatcherThread$AsyncDispatchTask.dispatchSomePendingHits(Unknown Source)
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): 	at com.google.android.apps.analytics.NetworkDispatcher$DispatcherThread$AsyncDispatchTask.run(Unknown Source)
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): 	at android.os.Handler.handleCallback(Handler.java:733)
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): 	at android.os.Handler.dispatchMessage(Handler.java:95)
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): 	at android.os.Looper.loop(Looper.java:212)
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): 	at android.os.HandlerThread.run(HandlerThread.java:61)
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): Caused by: libcore.io.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): 	at libcore.io.Posix.connect(Native Method)
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): 	at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:85)
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): 	at libcore.io.IoBridge.connectErrno(IoBridge.java:131)
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): 	at libcore.io.IoBridge.connect(IoBridge.java:116)
    12-20 16:55:17.845 W/GoogleAnalyticsTracker(8077): 	... 15 more
    12-20 16:55:17.925 W/ActivityManager(1374): Activity pause timeout for ActivityRecord{44971fe0 u0 com.aurora.store.legacy/com.aurora.store.ui.single.activity.GoogleLoginActivity t11 f}
    12-20 16:55:18.445 I/InputReader(1374): Reconfiguring input devices.  changes=0x00000010
    12-20 16:55:18.495 I/ActivityManager(1374): Delay finish: com.sonyericsson.facebook.proxylogin/.permissions.PackageChangedReceiver
    12-20 16:55:18.535 E/Parcel  (10872): Reading a NULL string not supported here.
    12-20 16:55:18.565 E/Parcel  (10872): Reading a NULL string not supported here.
    12-20 16:55:18.585 D/SonySWEffect(520): PARAM_CA_CHSEP Clear Stereo Off(0x80000001)
    12-20 16:55:18.585 D/SonySWEffect(520): Unsupported frame count 240
    12-20 16:55:18.595 I/Process (10703): Sending signal. PID: 10703 SIG: 9
    12-20 16:55:18.595 I/PackageManager(1374):   Action: "android.intent.action.SENDTO"
    12-20 16:55:18.595 I/PackageManager(1374):   Category: "android.intent.category.DEFAULT"
    12-20 16:55:18.595 I/PackageManager(1374):   Scheme: "sms"
    12-20 16:55:18.595 I/PackageManager(1374): Adding preferred activity ComponentInfo{org.smssecure.smssecure/org.smssecure.smssecure.SmsSendtoActivity} for user 0 :
    12-20 16:55:18.615 I/ActivityManager(1374): Process com.aurora.store.legacy (pid 10703) has died.
```

**Comment by johanw666** [comment]
Top, it works now.
